### ISSUE TITLE
download_historic_data choking

### ISSUE THREAD

**Issue by joethorley** [bcgov/rems#20]
```
> download_historic_data(force = TRUE, ask = FALSE)
This is going to take a while...
Downloading latest 'historic' EMS data from BC Data Catalogue (url:https://pub.data.gov.bc.ca/datasets/949f2233-9612-4b06-92a9-903e817da659/)
  |======================================================================================| 100%
Error in if (ext == ".zip") { : missing value where TRUE/FALSE needed
```

**Comment by ateucher** [comment]
Thanks for the report - I'll look into it

**Comment by ateucher** [comment]
Should be fixed @joethorley

**Comment by HeatherGranger** [comment]
@ateucher I'm still getting the same error message as @joethorley was getting earlier. 

> historic <- download_historic_data(force = TRUE, ask = FALSE)
This is going to take a while...
Downloading latest 'historic' EMS data from BC Data Catalogue (url:https://pub.data.gov.bc.ca/datasets/949f2233-9612-4b06-92a9-903e817da659/)
  |==============================================================================| 100%
Error in if (ext == ".zip") { : missing value where TRUE/FALSE needed

**Comment by ateucher** [comment]
That's funny - did you reinstall? (`devtools::install_github("bcgov/rems")`)

**Comment by HeatherGranger** [comment]
I had run:
 install_github("bcgov/rems") but it didn't reinstall. It worked with your code. Thanks!
